version: '2.1'

services:
  local:
    image: node:7.7.1-onbuild
    command: bash -c "npm run docker:dev"
    volumes:
      - .:/usr/src/app
    ports:
      - 3000:3000
    environment:
      NODE_ENV: development
      HTTP_PORT: 3000

  ci:
    build: .
    command: npm run docker:test
    volumes:
      - ./:/usr/src/app
    ports:
      - 3000:3000
    environment:
      NODE_ENV: test
      HTTP_PORT: 3000
      HTTP_HOST: '0.0.0.0'
